# Generated by Django 4.0.6 on 2022-07-08 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('company_name', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('company_phone', models.IntegerField()),
                ('company_address', models.CharField(max_length=300, verbose_name='Endereço da Empresa')),
                ('company_contact', models.CharField(max_length=100, verbose_name='Contato da Empresa')),
                ('company_mail', models.EmailField(max_length=254)),
                ('company_site', models.CharField(max_length=200, verbose_name='Site da Empresa')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
