# Generated by Django 4.0.6 on 2022-07-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pessoa_ativo_pessoa_criado_pessoa_modificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='area',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
